### ISSUE TITLE
I am your fan to China

### ISSUE THREAD

**Issue by huddhudd** [TJ888/PUBG-SDK#2]
I am your fan to China
I am a little white, see your SDK, do not know how to use, I want to achieve self-scanning and perspective. Can you give me some examples of source? Thank you. Mail To: ytjr@qq.com

**Comment by yk727228981** [comment]
老哥，你这机翻错的也太离谱了

**Comment by igromanru** [comment]
Any information you need, you can find in unknowncheats forum.

**Comment by Hecklezz** [comment]
This isn't an issue and therefore I will close it.
As Stated by igromanru, if you need help go to unknowncheats.

**Comment by TJ888** [comment]
This isn't an issue and therefore I am going to close it.
If you need help then as already stated by igromanru, go to UnknownCheats.

**Comment by jl2378** [comment]
Hi @TJ888. I need help SDK compile. I get "unresolved external symbol" very difficult can't build. pls HELP ty men.

**Comment by huddhudd** [comment]
I want to call this SDK through the driver, and I should know how to do it through the DLL injection, but I don't know the external way. I've been looking at it in the forums and haven't found it yet.

**Comment by TJ888** [comment]
Then make a thread on UC, state what you want to do and what you have already tried, potentially someone will help you.

I am not your personal cheat creator nor am I the person to tell you how to use it with your implementation of a cheat. It will be different for each person and how their stuff works.

**Comment by huddhudd** [comment]
m_UWorld  
g_GNames
What's the latest address?
